import AppKit

/// Polls NSPasteboard and reports new copies.
@MainActor
final class ClipboardMonitor {
    struct Snapshot {
        var kind: ClipKind
        var text: String
        var imageData: Data?
    }

    var onCopy: ((Snapshot, NSRunningApplication?) -> Void)?

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let settings: AppSettings

    /// Types that mean "do not store" (password managers, transient clipboards).
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
    ]

    init(settings: AppSettings) {
        self.settings = settings
    }

    func start() {
        stop()
        let t = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Ignore the next pasteboard change (the one we make ourselves).
    func acknowledgeOwnChange() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let app = NSWorkspace.shared.frontmostApplication
        if let bundleID = app?.bundleIdentifier, settings.ignoredApps.contains(bundleID) { return }
        guard let snapshot = read(pb) else { return }
        onCopy?(snapshot, app)
    }

    private func read(_ pb: NSPasteboard) -> Snapshot? {
        let types = (pb.types ?? []).map(\.rawValue)
        if types.contains(where: { Self.ignoredTypes.contains($0) }) { return nil }

        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return Snapshot(kind: .fileURL, text: urls.map(\.path).joined(separator: "\n"), imageData: nil)
        }

        if let string = pb.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return Snapshot(kind: .text, text: string, imageData: nil)
        }

        if let png = pb.data(forType: .png) {
            return Snapshot(kind: .image, text: "", imageData: png)
        }
        if let tiff = pb.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return Snapshot(kind: .image, text: "", imageData: png)
        }
        return nil
    }
}
